language: node_js
node_js:
  - 4.1.2
before_script:
  - gcc -v
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
compiler:
  - gcc
  - clang
sudo: false
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
addons:
  firefox: "39.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
